models:
    chat-gpt:
        config:
            anthropic_endpoint: ""
            api_endpoint: https://api.onefaka.com/v1
            api_key_env: CHAT_GPT_API_KEY
            model: gpt-5.5
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: openai
    deepseek:
        config:
            anthropic_endpoint: https://api.deepseek.com/anthropic
            api_endpoint: https://api.deepseek.com
            api_key_env: DEEPSEEK_API_KEY
            model: deepseek-v4-flash
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: deepseek
    deepsleep:
        config:
            anthropic_endpoint: ""
            api_endpoint: https://apiai.sztu.edu.cn/v1
            api_key_env: DEEPSLEEP_API_KEY
            model: deepseek-v4-pro
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: 学校
    minimax:
        config:
            anthropic_endpoint: https://api.minimaxi.com/anthropic
            api_endpoint: https://api.minimax.chat/v1
            api_key_env: MINIMAX_API_KEY
            model: MiniMax-M2.7
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: minimax
    minimax2.5:
        config:
            anthropic_endpoint: https://api.minimaxi.com/anthropic
            api_endpoint: https://api.minimax.chat/v1
            api_key_env: MINIMAX2.5_API_KEY
            model: minimax-M2.5
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: minimax
    qwen:
        config:
            api_endpoint: https://dashscope.aliyuncs.com/compatible-mode/v1
            api_key_env: DASHSCOPE_API_KEY
            model: qwen3.6-flash
            parameters:
                max_tokens: 4096
                temperature: 0.7
                top_p: 0.9
        enabled: true
        provider: dashscope
